---

- name: Install docker-py
  become: true
  pip:
    name: docker

- name: Create code Directory
  file: 
    path: '{{ role_path }}/code'
    state: directory
    mode: '0755'

- name: Get wikimedia code
  get_url:
    url: '{{ code_url }}'
    dest: '{{ role_path }}/code/{{ code_version }}.tar.gz'

- name: Unzip wikimedia
  unarchive:
    src: '{{ role_path }}/code/{{ code_version }}.tar.gz'
    dest: '{{ role_path }}/code/'

- name: Naming Conventions
  synchronize:
    src: '{{ role_path }}/code/{{ code_version }}'
    dest: '{{ playbook_dir }}/images/apache/wikimedia'

- name: Remove Code
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ role_path }}/code/{{ code_version }}.tar.gz'
    - '{{ role_path }}/code/{{ code_version }}'

- name: Build Docker image from Dockerfile
  docker_image:
    name: "{{ item.key }}"
    path: "{{ item.value }}"
    state: build
  with_dict: "{{ images }}"

- name: Remove Code
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ role_path }}/code/{{ code_version }}.tar.gz'
    - '{{ role_path }}/code/{{ code_version }}'
    - '{{ playbook_dir }}/images/apache/wikimedia'

